2022-11-19 22:52:49.956 DEBUG (SyncWorker_0) [homeassistant.util.yaml.loader] Secret latitude retrieved from secrets.yaml in folder /config
2022-11-19 22:52:49.956 DEBUG (SyncWorker_0) [homeassistant.util.yaml.loader] Secret longitude retrieved from secrets.yaml in folder /config
2022-11-19 22:52:49.959 DEBUG (SyncWorker_0) [homeassistant.util.yaml.loader] Secret http_trusted_proxy retrieved from secrets.yaml in folder /config
2022-11-19 22:52:49.960 DEBUG (SyncWorker_0) [homeassistant.util.yaml.loader] Secret rc_db_url retrieved from secrets.yaml in folder /config
2022-11-19 22:52:49.973 DEBUG (SyncWorker_0) [homeassistant.util.yaml.loader] Secret pb_api_key retrieved from secrets.yaml in folder /config
2022-11-19 22:52:49.973 DEBUG (SyncWorker_0) [homeassistant.util.yaml.loader] Secret tw_phone_no retrieved from secrets.yaml in folder /config
2022-11-19 22:52:49.974 DEBUG (SyncWorker_0) [homeassistant.util.yaml.loader] Secret tw_phone_no retrieved from secrets.yaml in folder /config
2022-11-19 22:52:49.975 DEBUG (SyncWorker_0) [homeassistant.util.yaml.loader] Secret in_username retrieved from secrets.yaml in folder /config
2022-11-19 22:52:49.975 DEBUG (SyncWorker_0) [homeassistant.util.yaml.loader] Secret in_password retrieved from secrets.yaml in folder /config
2022-11-19 22:52:49.999 DEBUG (SyncWorker_0) [homeassistant.util.yaml.loader] Secret ar_username retrieved from secrets.yaml in folder /config
2022-11-19 22:52:49.999 DEBUG (SyncWorker_0) [homeassistant.util.yaml.loader] Secret ar_password retrieved from secrets.yaml in folder /config
2022-11-19 22:52:49.999 DEBUG (SyncWorker_0) [homeassistant.util.yaml.loader] Secret ar_gm_user retrieved from secrets.yaml in folder /config
2022-11-19 22:52:49.999 DEBUG (SyncWorker_0) [homeassistant.util.yaml.loader] Secret ar_gm_password retrieved from secrets.yaml in folder /config
2022-11-19 22:52:50.000 DEBUG (SyncWorker_0) [homeassistant.util.yaml.loader] Secret tw_account_sid_from_twilio retrieved from secrets.yaml in folder /config
2022-11-19 22:52:50.000 DEBUG (SyncWorker_0) [homeassistant.util.yaml.loader] Secret tw_auth_token_from_twilio retrieved from secrets.yaml in folder /config
2022-11-19 22:52:50.050 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration swemail which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-19 22:52:50.050 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-19 22:52:50.050 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-19 22:52:50.051 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration husqvarna_automower which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-19 22:52:50.051 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sjofartsverket_viva which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-19 22:52:50.051 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nordpool which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-19 22:52:50.052 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-19 22:52:50.052 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration volkswagencarnet which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-19 22:52:50.052 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration aarlo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-19 22:52:50.053 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration blitzortung which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-19 22:52:50.053 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration gardena_smart_system which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-19 22:52:50.581 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=721 from 2022-11-19 21:13:47)
2022-11-19 22:52:52.794 ERROR (SyncWorker_4) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 22:52:58.999 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Shapes EEA3' for nanoleaf integration could not authenticate
2022-11-19 22:52:59.726 WARNING (MainThread) [homeassistant.config_entries] Config entry 'f9ecbc82-4a49-4efc-b32f-bf45a9dc72a8' for husqvarna_automower integration could not authenticate
2022-11-19 22:53:00.271 ERROR (MainThread) [tibber.tibber_home] Could not find consumption data.
2022-11-19 22:53:03.998 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Xiaomi Air Purifier 2S' for xiaomi_miio integration not ready yet: Unable to discover the device 192.168.86.153; Retrying in background
2022-11-19 22:53:07.112 WARNING (MainThread) [homeassistant.config_entries] Config entry 'TP2 HS110(EU)' for tplink integration not ready yet: Unable to connect to the device: 192.168.86.27: [Errno 113] Connect call failed ('192.168.86.27', 9999); Retrying in background
2022-11-19 22:53:11.233 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.motion_sensor_illuminance (lx) can not be converted to the unit of previously compiled statistics (Lux). Generation of long term statistics will be suppressed unless the unit changes back to Lux or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2022-11-19 22:53:53.014 ERROR (SyncWorker_7) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 22:54:53.025 ERROR (SyncWorker_1) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 22:55:53.027 ERROR (SyncWorker_6) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 22:56:53.019 ERROR (SyncWorker_3) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 22:57:53.016 ERROR (SyncWorker_0) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 22:58:53.033 ERROR (SyncWorker_3) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 22:59:53.041 ERROR (SyncWorker_10) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:00:53.020 ERROR (SyncWorker_9) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:01:53.023 ERROR (SyncWorker_4) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:02:53.020 ERROR (SyncWorker_11) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:03:53.055 ERROR (SyncWorker_1) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:04:53.030 ERROR (SyncWorker_1) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:05:53.035 ERROR (SyncWorker_0) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:06:53.036 ERROR (SyncWorker_6) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:07:53.044 ERROR (SyncWorker_3) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:08:53.061 ERROR (SyncWorker_10) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:09:53.044 ERROR (SyncWorker_11) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:10:53.036 ERROR (SyncWorker_2) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:11:53.051 ERROR (SyncWorker_4) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:12:53.042 ERROR (SyncWorker_2) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:13:00.191 ERROR (MainThread) [tibber.tibber_home] Could not find consumption data.
2022-11-19 23:13:53.096 ERROR (SyncWorker_7) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:14:53.066 ERROR (SyncWorker_10) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:15:53.047 ERROR (SyncWorker_3) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:16:53.097 ERROR (SyncWorker_5) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:17:53.049 ERROR (SyncWorker_3) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:18:07.537 WARNING (MainThread) [homeassistant.helpers.template] Distance:State does not contain valid location: <template TemplateState(<state device_tracker.zklvyzim_zigge=unavailable; icon=mdi:paw, friendly_name=Zigge-Älta Tracker @ 2022-11-19T23:18:07.536069+01:00>)>
2022-11-19 23:18:07.544 WARNING (MainThread) [homeassistant.helpers.template] Distance:State does not contain valid location: <template TemplateState(<state device_tracker.zklvyzim_zigge=unavailable; icon=mdi:paw, friendly_name=Zigge-Älta Tracker @ 2022-11-19T23:18:07.536069+01:00>)>
2022-11-19 23:18:53.050 ERROR (SyncWorker_3) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:19:51.292 WARNING (MainThread) [homeassistant.components.media_player] Updating samsungtv media_player took longer than the scheduled update interval 0:00:10
2022-11-19 23:19:51.293 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.samsung_led60_ue60f6300 is taking over 10 seconds
2022-11-19 23:19:53.069 ERROR (SyncWorker_10) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:20:53.035 ERROR (SyncWorker_4) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:21:53.082 ERROR (SyncWorker_5) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:22:53.046 ERROR (SyncWorker_1) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:23:21.619 WARNING (MainThread) [homeassistant.helpers.template] Distance:State does not contain valid location: <template TemplateState(<state device_tracker.zklvyzim_zigge=unavailable; icon=mdi:paw, friendly_name=Zigge-Älta Tracker @ 2022-11-19T23:23:21.617850+01:00>)>
2022-11-19 23:23:21.621 WARNING (MainThread) [homeassistant.helpers.template] Distance:State does not contain valid location: <template TemplateState(<state device_tracker.zklvyzim_zigge=unavailable; icon=mdi:paw, friendly_name=Zigge-Älta Tracker @ 2022-11-19T23:23:21.617850+01:00>)>
2022-11-19 23:23:53.064 ERROR (SyncWorker_5) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:24:53.050 ERROR (SyncWorker_4) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:25:53.070 ERROR (SyncWorker_3) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:26:53.088 ERROR (SyncWorker_3) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:27:53.062 ERROR (SyncWorker_8) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:28:53.071 ERROR (SyncWorker_10) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:29:55.720 WARNING (MainThread) [homeassistant.helpers.template] Distance:State does not contain valid location: <template TemplateState(<state device_tracker.zklvyzim_zigge=unavailable; icon=mdi:paw, friendly_name=Zigge-Älta Tracker @ 2022-11-19T23:29:55.718665+01:00>)>
2022-11-19 23:29:55.722 WARNING (MainThread) [homeassistant.helpers.template] Distance:State does not contain valid location: <template TemplateState(<state device_tracker.zklvyzim_zigge=unavailable; icon=mdi:paw, friendly_name=Zigge-Älta Tracker @ 2022-11-19T23:29:55.718665+01:00>)>
2022-11-19 23:30:01.129 WARNING (ArloEventStream) [pyaarlo] event loop timeout
2022-11-19 23:30:02.231 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.nuc7_temperature is taking over 10 seconds
2022-11-19 23:30:02.241 ERROR (SyncWorker_0) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pelle@192.168.86.76 'cat /sys/class/thermal/thermal_zone1/temp'
2022-11-19 23:30:02.592 ERROR (MainThread) [homeassistant.components.life360] Error fetching life360 (per.a.nordlund@gmail.com) data: TimeoutError
2022-11-19 23:30:02.601 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities fan.albins_fan or it is/they are currently not available
2022-11-19 23:30:02.604 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.albins_shapes or it is/they are currently not available
2022-11-19 23:30:03.110 WARNING (Thread-11) [pychromecast.socket_client] [Living room speaker(192.168.86.38):8009] Heartbeat timeout, resetting connection
2022-11-19 23:30:03.112 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.google_wifi_current_version is taking over 10 seconds
2022-11-19 23:30:03.120 WARNING (SyncWorker_2) [homeassistant.components.google_wifi.sensor] Unable to fetch data from Google Wifi
2022-11-19 23:30:03.552 WARNING (Thread-12) [pychromecast.socket_client] [Guest Room speaker(192.168.86.39):8009] Heartbeat timeout, resetting connection
2022-11-19 23:30:04.751 WARNING (Thread-9) [pychromecast.socket_client] [Upstairs TV(192.168.86.24):8009] Heartbeat timeout, resetting connection
2022-11-19 23:30:04.783 ERROR (MainThread) [homeassistant.components.glances] Unable to fetch data from Glances
2022-11-19 23:30:05.953 ERROR (SyncWorker_2) [homeassistant.components.command_line] Command failed (with return code 255): ssh -F /config/.ssh/config pi@192.168.86.45 'cat /sys/class/thermal/thermal_zone0/temp'
2022-11-19 23:30:06.396 WARNING (Thread-8) [pychromecast.socket_client] [Google TV(192.168.86.52):8009] Heartbeat timeout, resetting connection
